import type { Santri } from './types';

export const INITIAL_SANTRI_LIST: Santri[] = [
  {
    id: '1',
    name: 'Muhammad Faiz',
    nis: '2024001',
    juzAchieved: '14.5 Juz',
    linesCompletedToday: 15,
    dailyTargetLines: 12,
    totalLinesMemorized: 2175,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'An-Naba 1-40',
    avatarInitials: 'MF',
  },
  {
    id: '2',
    name: 'Bilal Al-Habasyi',
    nis: '2024004',
    juzAchieved: '12.0 Juz',
    linesCompletedToday: 12,
    dailyTargetLines: 10,
    totalLinesMemorized: 1800,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'At-Takwir 1-29',
    avatarInitials: 'BA',
  },
  {
    id: '3',
    name: 'Zaid bin Tsabit',
    nis: '2024005',
    juzAchieved: '18.2 Juz',
    linesCompletedToday: 15,
    dailyTargetLines: 15,
    totalLinesMemorized: 2730,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Yasin 1-45',
    avatarInitials: 'ZT',
  },
  {
    id: '4',
    name: 'Abdullah bin Mas\'ud',
    nis: '2024006',
    juzAchieved: '22.0 Juz',
    linesCompletedToday: 16,
    dailyTargetLines: 15,
    totalLinesMemorized: 3300,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Kahf 1-50',
    avatarInitials: 'AM',
  },
  {
    id: '5',
    name: 'Ali bin Abi Thalib',
    nis: '2024007',
    juzAchieved: '16.0 Juz',
    linesCompletedToday: 14,
    dailyTargetLines: 12,
    totalLinesMemorized: 2400,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Mulk 1-30',
    avatarInitials: 'AB',
  },
  {
    id: '6',
    name: 'Utsman bin Affan',
    nis: '2024008',
    juzAchieved: '25.0 Juz',
    linesCompletedToday: 20,
    dailyTargetLines: 15,
    totalLinesMemorized: 3750,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Baqarah 1-100',
    avatarInitials: 'UA',
  },
  {
    id: '7',
    name: 'Umar bin Khattab',
    nis: '2024009',
    juzAchieved: '19.5 Juz',
    linesCompletedToday: 15,
    dailyTargetLines: 14,
    totalLinesMemorized: 2925,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Ar-Rahman 1-78',
    avatarInitials: 'UK',
  },
  {
    id: '8',
    name: 'Sa\'ad bin Abi Waqqas',
    nis: '2024010',
    juzAchieved: '11.0 Juz',
    linesCompletedToday: 12,
    dailyTargetLines: 12,
    totalLinesMemorized: 1650,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Waqi\'ah 1-50',
    avatarInitials: 'SW',
  },
  {
    id: '9',
    name: 'Thalhah bin Ubaidillah',
    nis: '2024011',
    juzAchieved: '13.0 Juz',
    linesCompletedToday: 15,
    dailyTargetLines: 12,
    totalLinesMemorized: 1950,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Insan 1-31',
    avatarInitials: 'TU',
  },
  {
    id: '10',
    name: 'Zubair bin Awwam',
    nis: '2024012',
    juzAchieved: '10.5 Juz',
    linesCompletedToday: 13,
    dailyTargetLines: 12,
    totalLinesMemorized: 1575,
    totalLinesTarget: 9060,
    status: 'tercapai',
    lastSurah: 'Al-Qiyamah 1-40',
    avatarInitials: 'ZA',
  },
  {
    id: '11',
    name: 'Ahmad Zaki',
    nis: '2024002',
    juzAchieved: '8.5 Juz',
    linesCompletedToday: 6,
    dailyTargetLines: 15,
    totalLinesMemorized: 1275,
    totalLinesTarget: 9060,
    status: 'tidak_tercapai',
    lastSurah: 'An-Naziat 1-20',
    avatarInitials: 'AZ',
  },
  {
    id: '12',
    name: 'Farhan Ramadhan',
    nis: '2024003',
    juzAchieved: '5.2 Juz',
    linesCompletedToday: 0,
    dailyTargetLines: 15,
    totalLinesMemorized: 780,
    totalLinesTarget: 9060,
    status: 'belum_setor',
    lastSurah: 'Abasa 1-15 (Kemarin)',
    avatarInitials: 'FR',
  },
];
